<a href="https://colab.research.google.com/github/Steffenanderson/Machine-Learning-Exercises/blob/main/Regressor_Hackathon_Mercedes_Brand.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Regressor Hackathon

## Task

Your task is to build the best model possible using [this dataset](https://drive.google.com/file/d/12p39sSyrzxJtmH_1ycm-FotjjhCqyqAP/view?usp=sharing). Your goal is to predict the price of the cars using various information on the cars. You should be sure to validate your model. The winning team will build a model with the lowest testing RMSE.

The data given is from [Kaggle](https://www.kaggle.com/adityadesai13/used-car-dataset-ford-and-mercedes?select=merc.csv) and describes prices of Mercedes brand cars.

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor

df = pd.read_csv('/content/drive/MyDrive/merc.csv')

print(df.head())
print(df.info())

print(df['model'].value_counts())
print(df['fuelType'].value_counts())

# df.drop(columns=['fuelType'] == 'other')
# print(df.info())

temp = df.loc[:,'fuelType'] == 'Other'
print(temp)
df = df.loc[~temp, :]
print(df.info())

# df.drop(columns = 'price')
print(df.duplicated().any())
df.duplicated().any()
df = df.drop_duplicates()
print(df.info())

y = df['price'].values
X = df.drop(columns = 'price')


OneHotEncoder = pd.get_dummies(X, columns = ['model', 
                                            'transmission', 
                                            'fuelType'],
                                            drop_first = True)
X = OneHotEncoder.loc[:,:].values                                            
print(y.shape)
print(X.shape)


X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=3)

reg = LinearRegression(fit_intercept=True)
reg.fit(X_train,y_train)
score = reg.score(X_train, y_train)
print(score)
score = reg.score(X_test,y_test)
predictions = reg.predict(X_test)
print(score)
print(np.sqrt(mean_squared_error(y_test,predictions)))


rf_reg = RandomForestRegressor(n_estimators=50, bootstrap=True, oob_score=True)
rf_reg.fit(X_train, y_train)
score = rf_reg.score(X_train, y_train)
print("X_train rf_reg", score)
score = rf_reg.score(X_test, y_test)
print("X_test rf_reg", score)
predictions = rf_reg.predict(X_test)
print("rmsqe rf_reg",np.sqrt(mean_squared_error(y_test,predictions)))

       model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0        SLK  2005   5200    Automatic    63000   Petrol  325  32.1         1.8
1    S Class  2017  34948    Automatic    27000   Hybrid   20  61.4         2.1
2   SL CLASS  2016  49948    Automatic     6200   Petrol  555  28.0         5.5
3    G Class  2016  61948    Automatic    16000   Petrol  325  30.4         4.0
4    G Class  2016  73948    Automatic     4000   Petrol  325  30.1         4.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13119 entries, 0 to 13118
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   model         13119 non-null  object
 1   year          13119 non-null  int64
 2   price         13119 non-null  int64
 3   transmission  13119 non-null  object
 4   mileage       13119 non-null  int64
 5   fuelType      13119 non-null  object
 6   tax           13119 non-null  int64
 7   mpg           13119 non-null  float64
 8   engineSize    13119 non-null  float64
dtypes: float64(2), int64(4), object(3)
memory usage: 922.6+ KB
None
 C Class      3747
 A Class      2561
 E Class      1953
 GLC Class     960
 GLA Class     847
 B Class       591
 CL Class      511
 GLE Class     461
 SL CLASS      260
 CLS Class     237
 V Class       207
 S Class       197
 GL Class      121
 SLK            95
 CLA Class      86
 X-CLASS        82
 M Class        79
 GLS Class      74
 GLB Class      19
 G Class        15
 CLK             7
 CLC Class       3
 R Class         2
180              1
220              1
200              1
230              1
Name: model, dtype: int64
Diesel    9187
Petrol    3752
Hybrid     173
Other        7
Name: fuelType, dtype: int64
0        False
1        False
2        False
3        False
4        False
         ...
13114    False
13115    False
13116    False
13117    False
13118    False
Name: fuelType, Length: 13119, dtype: bool
<class 'pandas.core.frame.DataFrame'>
Int64Index: 13112 entries, 0 to 13118
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   model         13112 non-null  object
 1   year          13112 non-null  int64
 2   price         13112 non-null  int64
 3   transmission  13112 non-null  object
 4   mileage       13112 non-null  int64
 5   fuelType      13112 non-null  object
 6   tax           13112 non-null  int64
 7   mpg           13112 non-null  float64
 8   engineSize    13112 non-null  float64
dtypes: float64(2), int64(4), object(3)
memory usage: 1.0+ MB
None
True
<class 'pandas.core.frame.DataFrame'>
Int64Index: 12853 entries, 0 to 13118
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   model         12853 non-null  object
 1   year          12853 non-null  int64
 2   price         12853 non-null  int64
 3   transmission  12853 non-null  object
 4   mileage       12853 non-null  int64
 5   fuelType      12853 non-null  object
 6   tax           12853 non-null  int64
 7   mpg           12853 non-null  float64
 8   engineSize    12853 non-null  float64
dtypes: float64(2), int64(4), object(3)
memory usage: 1004.1+ KB
None
(12853,)
(12853, 36)
0.769770419568957
0.763671675400308
5751.947268978565
X_train rf_reg 0.9919932192467544
X_test rf_reg 0.9516868049910692
rmsqe rf_reg 2600.6977823823463